name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    -
      name: Set Bundle
      run: |
        gem update --system
        gem install bundler
    -
      name: Bundle Install
      run: |
        bundle install --jobs 4 --retry 3
        bundle lock --add-platform x86_64-linux
        bundle update net-pop
        bundle update

    - name: Run the default task
      run: bundle exec rake
